const tests=[{name:"CBC Test",cat:"blood",desc:"Routine complete blood count screening.",tag:"Blood"},{name:"Liver Function Test",cat:"blood",desc:"Common liver health screening.",tag:"Blood"},{name:"Kidney Function Test",cat:"blood",desc:"Routine kidney function screening.",tag:"Blood"},{name:"Fasting Blood Sugar",cat:"blood",desc:"Glucose screening with a fasting sample.",tag:"Blood"},{name:"HbA1c",cat:"wellness",desc:"Longer-term glucose monitoring marker.",tag:"Wellness"},{name:"Thyroid Profile",cat:"thyroid",desc:"T3, T4 and TSH screening.",tag:"Thyroid"},{name:"Vitamin D",cat:"vitamins",desc:"Vitamin D level testing.",tag:"Vitamins"},{name:"Vitamin B12",cat:"vitamins",desc:"Vitamin B12 level assessment.",tag:"Vitamins"},{name:"Lipid Profile",cat:"wellness",desc:"Cholesterol and triglyceride screening.",tag:"Wellness"},{name:"Urine Routine",cat:"wellness",desc:"Routine urine analysis.",tag:"Wellness"},{name:"Full Body Checkup",cat:"wellness",desc:"Demo preventive screening package.",tag:"Wellness"}];
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s)); const grid=$("#testGrid"),search=$("#testSearch"),clear=$("#clearSearch"),filters=$$(".filter");
function icons(){if(window.lucide?.createIcons)window.lucide.createIcons()}
function render(){if(!grid)return;const q=(search?.value||"").trim().toLowerCase(),f=$(".filter.active")?.dataset.filter||"all";const rows=tests.filter(t=>(f==="all"||t.cat===f)&&(!q||(t.name+" "+t.desc+" "+t.tag).toLowerCase().includes(q)));grid.innerHTML=rows.length?rows.map(t=>'<article class="test-card"><span class="test-tag">'+t.tag+'</span><h3>'+t.name+'</h3><p>'+t.desc+'</p><a href="#booking" class="test-link" data-test="'+t.name+'">Ask about this <i data-lucide="arrow-right"></i></a></article>').join(""):'<div class="empty-state">No matching test found.</div>';icons()}
function menu(){const b=$("#menuToggle"),m=$("#mobileMenu");if(!b||!m)return;b.addEventListener("click",()=>{const open=m.classList.toggle("open");document.body.classList.toggle("menu-open",open);b.setAttribute("aria-expanded",open);m.setAttribute("aria-hidden",!open);b.innerHTML='<i data-lucide="'+(open?"x":"menu")+'"></i>';icons()});$$(".mobile-menu a").forEach(a=>a.addEventListener("click",()=>{m.classList.remove("open");document.body.classList.remove("menu-open");b.setAttribute("aria-expanded","false");m.setAttribute("aria-hidden","true");b.innerHTML='<i data-lucide="menu"></i>';icons()}))}
function reveal(){const els=$$(".reveal");if(!("IntersectionObserver"in window)){els.forEach(e=>e.classList.add("is-visible"));return}const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");o.unobserve(e.target)}}),{threshold:.08,rootMargin:"0px 0px -6%"});els.forEach(e=>o.observe(e))}
filters.forEach(f=>f.addEventListener("click",()=>{filters.forEach(x=>x.classList.remove("active"));f.classList.add("active");render()}));search?.addEventListener("input",render);clear?.addEventListener("click",()=>{search.value="";render();search.focus()});
$("#heroSearchButton")?.addEventListener("click",()=>{$("#tests")?.scrollIntoView({behavior:"smooth"});if(search)search.value=$("#heroSearch").value;render()});$("#heroSearch")?.addEventListener("keydown",e=>{if(e.key==="Enter")$("#heroSearchButton").click()});
document.addEventListener("click",e=>{const t=e.target.closest("[data-test]"),p=e.target.closest("[data-package]");if(t)localStorage.setItem("demo_selected",t.dataset.test);if(p)localStorage.setItem("demo_selected",p.dataset.package)});
$(".demo-report")?.addEventListener("click",()=>alert("Demo only — connect this button to the client's secure report system."));
$("#bookingForm")?.addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.currentTarget),m=["Hello, I would like to enquire.","Name: "+(d.get("name")||""),"Phone: "+(d.get("phone")||""),"Need: "+(d.get("need")||""),localStorage.getItem("demo_selected")?"Selected: "+localStorage.getItem("demo_selected"):"","Message: "+(d.get("message")||"")].filter(Boolean).join("\n");window.open("https://wa.me/?text="+encodeURIComponent(m),"_blank")});
function lang(){ $$(".lang-button").forEach(b=>b.addEventListener("click",()=>{document.cookie=b.dataset.lang==="en"?"googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;":"googtrans=/en/"+b.dataset.lang+"; path=/";location.reload()}))}
render();menu();reveal();lang();icons();